name: Data Update

on:
  push:
    branches:
      - main

jobs:
  data-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install virtualenv
          virtualenv env --python=python3
          env/bin/pip install -r requirements.txt

      - name: Run update script
        run: |
          git pull
          bash ./fetch-updates.sh -n -p -u ${{ secrets.GIT_USERNAME }} -w ${{ secrets.GIT_PASSWORD }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Data update"
          branch: ${{ github.ref }}
          commit_options: "--no-verify"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
