name: 🥳 New CVE List

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour at the start of the hour
  
  workflow_dispatch:

jobs:
  templates:
    runs-on: ubuntu-latest
    if: github.repository == 'CVEList/update'
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - name: Install Dependences
        run: |
            sudo apt install -yy python3
            python3 -m venv env
            source env/bin/activate

      - name: Generate new CVE Info list
        id: new-additions
        run: |
          git pull
          chmod +x install.sh
          ./install.sh
          chmod +x fetch-updates.sh
          bash fetch-updates.sh -p -u ${{ secrets.GIT_USERNAME }} -w ${{ secrets.GIT_PASSWORD }}
